OBJECT_INTERPRETATIONS = {
    # Axes & Points
    "Ascendant": "The Identity Interface & body-OS bootloader",
    "Descendant": "The Mirror Port for one-to-one contracts & co-regulation",
    "MC": "The Public Interface & executive mission panel",
    "IC": "The Root System & ancestral memory vault",
    "True Node": "The Northbound Vector—evolutionary growth protocol",
    "South Node": "The Ancestral Cache—purge/compost valve for over-learned patterns",
    "Vertex": "The Fate Dock—improbable convergence node",
    "Part of Fortune": "The Ease Circuit—low-friction throughput and natural gains",
    "Black Moon Lilith": "The Primal Sovereignty Field—boundary breaker & untamed voltage",

    # Luminaries & Planets
    "Sun": "The Core Reactor & mission kernel",
    "Moon": "The Autonomic Regulator & memory tide",
    "Mercury": "The Signal Router & cognitive codec",
    "Venus": "The Attractor Engine & coherence field",
    "Mars": "The Drive Actuator & ignition vector",
    "Jupiter": "The Meaning Amplifier & growth protocol",
    "Saturn": "The Constraint Architect, time-keeper, & form-governor",
    "Uranus": "The Update Daemon & liberation current",
    "Neptune": "The Dream Renderer & dissolution cloud",
    "Pluto": "The Underworld Compiler & power transmuter",

    # Healing, devotion, sovereignty
    "Ceres": "The Nurture Protocol—cyclical provisioning & metabolic care",
    "Pallas": "The Pattern-Recognition Engine—tactical design & creative strategy",
    "Juno": "The Bond-Contract Manager—commitment format & loyalty spec",
    "Vesta": "The Sacred Focus Kernel—devotional flame & consecrated attention",
    "Lilith": "The Raw Sovereign Impulse—taboo breaker & reclamation surge",
    "Chiron": "The Wound-into-Medicine Bridge—remediation key & apprenticeship path",

    # Muses, arts, memory
    "Iris": "The Spectrum Messenger—bridge-and-translate across bands",
    "Hygiea": "The Sanitation Routine—detox scheduler & systems hygiene",
    "Psyche": "The Deep-Sensing Kernel—bonding depth & intimacy decoder",
    "Thalia": "The Levity Driver—resilience via wit & comedic reframing",
    "Euterpe": "The Melodic Intake—breath-of-inspiration & lyrical flow",
    "Pomona": "The Harvest Module—cultivation, ripeness, and stewardship",
    "Polyhymnia": "The Devotional Channel—sacred rhetoric & potent silence",
    "Harmonia": "The Coherence Balancer—conflict resolver & tonal tuning",
    "Isis": "The Reassembly Protocol—sacred naming & wholeness restoration",
    "Ariadne": "The Labyrinth Navigator—thread management & escape design",
    "Mnemosyne": "The Ancestral Memory Vault—recall indexer & storykeeper",
    "Echo": "The Reflection Loop—call-and-response mapper & resonance check",
    "Niobe": "The Pride-Collapse Lesson—grief calculus & softening cue",
    "Eurydike": "The Underworld Trust Test—retrieval boundary & consent line",
    "Freia": "The Magnetic Allure Field—sovereignty barter & desire economy",
    "Terpsichore": "The Kinetic Rhythm Driver—body-poetry and motion grammar",
    "Minerva": "The Strategic Wisdom Stack—invention schematic & clear seeing",
    "Hekate": "The Threshold Keyring—gate choice, liminal craft, and crossings",
    "Zephyr": "The Gentle Tailwind—signal aeration & effortless drift",
    "Kassandra": "The Unheeded Warning Flag—truth persistence amid noise",
    "Lachesis": "The Timeline Allocator—scope limiter & lifespan apportioner",
    "Nemesis": "The Overreach Corrector—consequences returning to balance",
    "Medusa": "The Gorgon Shield—petrify-to-protect and gaze discipline",
    "Aletheia": "The Disclosure Engine—truth-reveal toggle & clarity lock",
    "Magdalena": "The Redemptive Devotion—eros-as-medicine & lineage healing",
    "Arachne": "The Network Weaver—craft mastery & web-logic (hubris check)",
    "Fama": "The Signal Amplifier—reputation wave & rumor dynamics",
    "Eros": "The Desire Vector—life-force aim & attractive precision",
    "Veritas": "The Integrity Seal—verification checksum & honesty clamp",

    # Makers, rebels, risk
    "Hidalgo": "The Outlaw Ethic—boundary testing & frontier justice",
    "Sirene": "The Siren Call—magnetic lure & navigation of allure tests",
    "Siva": "The Destruction-Creation Pulse—ascetic focus & renewal cycle",
    "Lilith (Asteroid)": "The Embodied Rebel Muse—raw feminine actuator in form",
    "Copernicus": "The Paradigm Pivot Engine—heliocentric reframe & model swap",
    "Icarus": "The Risk-Altitude Gauge—ambition burn limit & heat handling",
    "Toro": "The Raw Torque Channel—stamina, potency, and applied force",
    "Apollo": "The Solar Artistry Beam—precision targeting & performance craft",
    "Koussevitzky": "The Orchestration Lead—ensemble coordination & baton logic",
    "Anteros": "The Reciprocity Circuit—love returned & mutuality check",
    "Tezcatlipoca": "The Obsidian Mirror—shadow tracking & trickster resets",

    # Transpersonal & mythic tech
    "Varuna": "The Cosmic Lawwave—oath-keeping and fluid jurisdiction",
    "West": "The Occidental Vector—dusk-phase transitions & endings craft",
    "Bacchus": "The Ecstatic Release—fermentation, intoxication, and rite",
    "Hephaistos": "The Forge Lab—smithing, prosthetics, and repair invention",
    "Panacea": "The Universal Remedy Hypothesis—integrative fix attempts",
    "Orpheus": "The Music-as-Spell—underworld diplomacy via song",
    "Kafka": "The Metamorphosis Trigger—bureaucracy maze & surreal insight",
    "Pamela": "The Image-Magic Conduit—tarot language & symbolic art channel",
    "Dionysus": "The Ritual Intoxication—boundary dissolution & holy madness",
    "Kaali": "The Serpent Current Monitor—kundalini surge & power handling",
    "Asclepius": "The Clinical Healer Code—crisis medicine & precise repair",
    "Nessus": "The Boundary-Violation Pattern—accountability switch & cycle break",
    "Singer": "The Vocal Node—signature timbre antenna & songcraft focus",
    "Angel": "The Messenger Light Node—protection ping & benevolent signal",
    "Ixion": "The Second-Chance Engine—taboo breaker audit & redemption test",
    "Typhon": "The Primordial Storm Generator—chaos fields & reset weather",
    "Quaoar": "The Creation-Dance Coder—joyful order from primal noise",
    "Sedna": "The Exile Wound Archive—slow-time sovereignty & oceanic depth",
    "Orcus": "The Oath Ledger—underworld contracts & promise enforcement",
    "Haumea": "The Crystalline Birth Matrix—rapid regeneration & lineage splitting",
    "Eris": "The Disruption Catalyst—naming-rights challenger & schism maker",
    "Makemake": "The Ritual Provisioner—island-ecology creativity & feast codes"
}
